# Copyright 2026 Huawei Technologies Co., Ltd
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ============================================================================
"""Emit fixed numerical recipe context initialization and explicit cleanup blocks."""

from __future__ import annotations

import json
import re
import textwrap
from pathlib import Path

CORE = Path(__file__).resolve().parents[1]
_CONTRACTS = CORE / "runtime/worker_calls.json"
_HEADER = ("// Copyright 2026 Huawei Technologies Co., Ltd.\n"
           "// Licensed under the Apache License, Version 2.0.\n"
           "// http://www.apache.org/licenses/LICENSE-2.0\n"
           "// Generated by backends.contexts; edit runtime/worker_calls.json.\n")


def _contracts():
    workers = json.loads(_CONTRACTS.read_text())["workers"]
    owners = {"callback_local", "borrowed_pipe_and_instance", "worker_owned", "stage_local", "borrowed_pipe"}
    for name, worker in workers.items():
        for key, context in worker.get("contexts", {}).items():
            source = context.get("source", Path(worker["source"]).name)
            phases = context["phases"]
            if (Path(source).name != source or source in {".", ".."}
                    or re.fullmatch(r"\w+", key) is None
                    or context["ownership"] not in owners
                    or not phases or not set(phases).issubset({"init", "finish"})
                    or any(not statements.strip() for statements in phases.values())):
                raise ValueError(f"Invalid native context contract: {name}/{key}")
    return workers


def generated_files() -> dict[Path, str]:
    """Emit initialization and cleanup in the original caller-owned local scope."""
    workers = _contracts()
    files = {}
    for name, worker in workers.items():
        for key, context in worker.get("contexts", {}).items():
            for phase, statements in context["phases"].items():
                lines = [wrapped for line in statements.splitlines()
                         for wrapped in textwrap.wrap(line.strip(), width=78, subsequent_indent="    ",
                                                      break_long_words=False, break_on_hyphens=False)]
                path = Path(f"ops/runtime/generated/{name}_{key}_{phase}_context.inc")
                files[path] = _HEADER + "\n".join(lines) + "\n"
    return files


def _method(text, name):
    matches = list(re.finditer(rf"\bvoid\s+{re.escape(name)}\s*\(", text))
    if len(matches) != 1:
        raise ValueError(f"Native context method missing or ambiguous: {name}")
    start = matches[0].start()
    opening = text.index("{", matches[0].end())
    end, depth = opening + 1, 1
    while depth:
        depth += (text[end] == "{") - (text[end] == "}")
        end += 1
    return text[start:end]


def adapt_contexts(text: str, name: str, source: str | None = None) -> str:
    """Install admitted setup/cleanup blocks without changing primitive execution or pipe-reset order.

    Args:
        text: Already verified original native worker source.
        name: Family/direction key in the shared worker contract.
        source: Sibling source basename; None selects the main worker source.
    """
    worker = _contracts()[name]
    default_source = Path(worker["source"]).name
    selected_source = default_source if source is None else source
    for key, context in worker.get("contexts", {}).items():
        if context.get("source", default_source) != selected_source:
            continue
        method = _method(text, context["method"])
        original = method
        for phase, statements in context["phases"].items():
            pattern = r"\s+".join(re.escape(word) for word in statements.split())
            matches = list(re.finditer(pattern, method))
            if len(matches) != 1:
                raise ValueError(f"Native context {phase} contract drift: {name}/{key}")
            path = f"runtime/generated/{name}_{key}_{phase}_context.inc"
            method = method[:matches[0].start()] + f'#include "{path}"' + method[matches[0].end():]
        text = text.replace(original, method, 1)
    return text


def install_context_glue(kernel: Path, name: str) -> None:
    """Admit all sibling context sources before installing any adapted source.

    Args:
        kernel: Isolated operator op_kernel directory with generated fragments.
        name: Family/direction key in the shared worker contract.
    """
    worker = _contracts()[name]
    sources = {context.get("source", Path(worker["source"]).name)
               for context in worker.get("contexts", {}).values()}
    adapted = {kernel / source: adapt_contexts((kernel / source).read_text(), name, source)
               for source in sorted(sources)}
    for path, text in adapted.items():
        path.write_text(text)
