# Copyright 2026 Huawei Technologies Co., Ltd
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ============================================================================
"""Emit fixed numerical recipe context initialization and explicit cleanup blocks."""

from __future__ import annotations

import json
import re
import textwrap
from pathlib import Path

CORE = Path(__file__).resolve().parents[1]
_CONTRACTS = CORE / "runtime/worker_calls.json"
_HEADER = ("// Copyright 2026 Huawei Technologies Co., Ltd.\n"
           "// Licensed under the Apache License, Version 2.0.\n"
           "// http://www.apache.org/licenses/LICENSE-2.0\n"
           "// Generated by backends.contexts; edit runtime/worker_calls.json.\n")


def generated_files() -> dict[Path, str]:
    """Emit initialization and cleanup in the original caller-owned local scope."""
    workers = json.loads(_CONTRACTS.read_text())["workers"]
    files = {}
    for name, worker in workers.items():
        for key, context in worker.get("contexts", {}).items():
            for phase, statements in context["phases"].items():
                lines = [wrapped for line in statements.splitlines()
                         for wrapped in textwrap.wrap(line.strip(), width=78, subsequent_indent="    ",
                                                      break_long_words=False, break_on_hyphens=False)]
                path = Path(f"ops/runtime/generated/{name}_{key}_{phase}_context.inc")
                files[path] = _HEADER + "\n".join(lines) + "\n"
    return files


def _method(text, name):
    start = text.index("void " + name + "(")
    opening = text.index("{", start)
    end, depth = opening + 1, 1
    while depth:
        depth += (text[end] == "{") - (text[end] == "}")
        end += 1
    return text[start:end]


def adapt_contexts(text: str, name: str) -> str:
    """Install admitted setup/cleanup blocks without changing primitive execution or pipe-reset order.

    Args:
        text: Already verified original native worker source.
        name: Family/direction key in the shared worker contract.
    """
    worker = json.loads(_CONTRACTS.read_text())["workers"][name]
    for key, context in worker.get("contexts", {}).items():
        method = _method(text, context["method"])
        original = method
        for phase, statements in context["phases"].items():
            pattern = r"\s+".join(re.escape(word) for word in statements.split())
            matches = list(re.finditer(pattern, method))
            if len(matches) != 1:
                raise ValueError(f"Native context {phase} contract drift: {name}/{key}")
            path = f"runtime/generated/{name}_{key}_{phase}_context.inc"
            method = method[:matches[0].start()] + f'#include "{path}"' + method[matches[0].end():]
        text = text.replace(original, method, 1)
    return text
