# Copyright 2026 Huawei Technologies Co., Ltd
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ============================================================================
"""Emit fixed primitive context setup, factory definitions and explicit cleanup."""

from __future__ import annotations

import json
import re
import textwrap
from pathlib import Path, PurePosixPath

CORE = Path(__file__).resolve().parents[1]
_CONTRACTS = CORE / "runtime/worker_calls.json"
_HEADER = ("// Copyright 2026 Huawei Technologies Co., Ltd.\n"
           "// Licensed under the Apache License, Version 2.0.\n"
           "// http://www.apache.org/licenses/LICENSE-2.0\n"
           "// Generated by backends.contexts; edit runtime/worker_calls.json.\n")


def _valid_source(source):
    path = PurePosixPath(source)
    return (not path.is_absolute() and ".." not in path.parts and str(path) == source
            and bool(path.name) and source != "." and "\\" not in source)


def _validate_context(name, key, context, source):
    phases = context["phases"]
    allowed = {"definition"} if context.get("scope", "function") == "macro" else {"init", "finish"}
    occurrences = context.get("occurrences", 1)
    if (not _valid_source(source) or re.fullmatch(r"\w+", key) is None
            or context.get("scope", "function") not in {"function", "macro"}
            or not isinstance(occurrences, int) or isinstance(occurrences, bool) or occurrences < 1
            or not phases or not set(phases).issubset(allowed)
            or any(not statements.strip() for statements in phases.values())):
        raise ValueError(f"Invalid native context contract: {name}/{key}")


def _contracts():
    workers = json.loads(_CONTRACTS.read_text())["workers"]
    owners = {"callback_local", "borrowed_pipe_and_instance", "worker_owned", "stage_local", "borrowed_pipe"}
    for name, worker in workers.items():
        for key, context in worker.get("contexts", {}).items():
            source = context.get("source", Path(worker["source"]).name)
            if context["ownership"] not in owners:
                raise ValueError(f"Invalid native context contract: {name}/{key}")
            _validate_context(name, key, context, source)
    return workers


def generated_files() -> dict[Path, str]:
    """Emit initialization and cleanup in the original caller-owned local scope."""
    workers = _contracts()
    files = {}
    for name, worker in workers.items():
        for key, context in worker.get("contexts", {}).items():
            for phase, statements in context["phases"].items():
                lines = [wrapped for line in statements.splitlines()
                         for wrapped in textwrap.wrap(line.strip(), width=78, subsequent_indent="    ",
                                                      break_long_words=False, break_on_hyphens=False)]
                if phase == "definition":
                    lines = [line + (" \\" if index < len(lines) - 1 else "")
                             for index, line in enumerate(lines)]
                path = Path(f"ops/runtime/generated/{name}_{key}_{phase}_context.inc")
                files[path] = _HEADER + "\n".join(lines) + "\n"
    return files


def _method(text, name):
    matches = list(re.finditer(rf"\bvoid\s+{re.escape(name)}\s*\(", text))
    if len(matches) != 1:
        raise ValueError(f"Native context method missing or ambiguous: {name}")
    start = matches[0].start()
    opening = text.index("{", matches[0].end())
    end, depth = opening + 1, 1
    while depth:
        depth += (text[end] == "{") - (text[end] == "}")
        end += 1
    return text[start:end]


def _macro(text, name):
    matches = list(re.finditer(rf"^#define\s+{re.escape(name)}\(", text, re.MULTILINE))
    if len(matches) != 1:
        raise ValueError(f"Native context macro missing or ambiguous: {name}")
    start = matches[0].start()
    end = text.index("\n", start)
    while text[start:end].rstrip().endswith("\\"):
        end = text.index("\n", end + 1)
    return text[start:end]


def _adapt_phase(method, statements, context, include, label, phase):
    if phase == "definition":
        normalized = "".join(method.replace("\\\n", " ").split())
        if normalized != "".join(statements.split()):
            raise ValueError(f"Native context definition contract drift: {label}")
        return include
    pattern = r"\s+".join(re.escape(word) for word in statements.split())
    matches = list(re.finditer(pattern, method))
    if len(matches) != context.get("occurrences", 1):
        raise ValueError(f"Native context {phase} contract drift: {label}")
    for match in reversed(matches):
        method = method[:match.start()] + include + method[match.end():]
    return method


def adapt_contexts(text: str, name: str, source: str | None = None) -> str:
    """Install admitted setup/cleanup blocks without changing primitive execution or pipe-reset order.

    Args:
        text: Verified original native worker, pipeline or primitive source.
        name: Family/direction key in the shared worker contract.
        source: Relative kernel source path; None selects the main worker source.
    """
    worker = _contracts()[name]
    default_source = Path(worker["source"]).name
    selected_source = default_source if source is None else source
    for key, context in worker.get("contexts", {}).items():
        if context.get("source", default_source) != selected_source:
            continue
        method = (_macro if context.get("scope") == "macro" else _method)(text, context["method"])
        original = method
        for phase, statements in context["phases"].items():
            prefix = "../" * len(PurePosixPath(selected_source).parent.parts)
            path = f"{prefix}runtime/generated/{name}_{key}_{phase}_context.inc"
            method = _adapt_phase(method, statements, context, f'#include "{path}"', f"{name}/{key}", phase)
        text = text.replace(original, method, 1)
    return text


def install_context_glue(kernel: Path, name: str) -> None:
    """Admit all relative context sources before installing any adapted source.

    Args:
        kernel: Isolated operator op_kernel directory with generated fragments.
        name: Family/direction key in the shared worker contract.
    """
    worker = _contracts()[name]
    sources = {context.get("source", Path(worker["source"]).name)
               for context in worker.get("contexts", {}).values()}
    adapted = {kernel / source: adapt_contexts((kernel / source).read_text(), name, source)
               for source in sorted(sources)}
    for path, text in adapted.items():
        path.write_text(text)
