# Copyright 2026 Huawei Technologies Co., Ltd
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ============================================================================
"""Generate native and Meta launchers from the shared dispatcher and ownership schema."""

from __future__ import annotations

import argparse
import json
import re
import textwrap
from pathlib import Path

import torch

from hyper_parallel.core.multicore.backends.workers import _tokens

CORE = Path(__file__).resolve().parents[1]
_CALLS = CORE / "runtime/native_calls.json"
_HEADER = ("// Copyright 2026 Huawei Technologies Co., Ltd.\n"
           "// Licensed under the Apache License, Version 2.0.\n"
           "// http://www.apache.org/licenses/LICENSE-2.0\n"
           "// Generated by backends.launchers; edit runtime/native_calls.json.\n")
_TYPES = {"Tensor": "const at::Tensor&", "int": "int64_t", "float": "double", "bool": "bool"}


def _entries(family=None):
    entries = json.loads(_CALLS.read_text())["entries"]
    result = {name: entry for name, entry in entries.items() if family is None or entry["family"] == family}
    if not result:
        raise ValueError(f"Unsupported native launcher family: {family}")
    for name, entry in result.items():
        _validate_entry(name, entry)
    return result


def _validate_entry(name, entry):
    launcher = entry["launcher"]
    arguments = {arg["name"]: arg for arg in entry["arguments"]}
    owned = {output["name"] for output in launcher["owned_outputs"]}
    returns = launcher["return_arguments"]
    if len(returns) != len(entry["returns"]) or not set(returns).issubset(arguments.keys() | owned):
        raise ValueError(f"Native launcher return ownership mismatch: {name}")
    if set(launcher["native_arguments"]) != arguments.keys() | owned:
        raise ValueError(f"Native launcher argument coverage mismatch: {name}")
    parsed = torch._C.parse_schema(entry["schema"])
    for returned, actual in zip(returns, parsed.returns):
        if actual.alias_info is None:
            valid = returned in owned
        else:
            argument = next(arg for arg in parsed.arguments if arg.name == returned)
            valid = (argument.alias_info is not None
                     and argument.alias_info.before_set == actual.alias_info.before_set)
        if not valid:
            raise ValueError(f"Native launcher alias contract mismatch: {name}")


def launcher_manifest(family: str) -> dict[str, object]:
    """Describe output ownership, ordered ACLNN arguments and selected native bridge.

    Args:
        family: Supported operator family.
    """
    return {"format_version": 1, "family": family,
            "entries": {name: entry["launcher"] for name, entry in _entries(family).items()}}


def _function_name(entry, backend):
    launcher = entry["launcher"]
    return launcher["cpp_name"] + (backend.capitalize() if entry["family"] == "gate" else "_" + backend)


def _return_type(name, entry):
    if len(entry["returns"]) == 1:
        return "at::Tensor", ""
    alias = name + "_outputs"
    return alias, ("using hyper_parallel::multicore::generated::LauncherOutputs;\n"
                   + f"using {alias} = LauncherOutputs::{alias};\n")


def _body(entry, backend, return_type):
    launcher = entry["launcher"]
    lines = []
    validation = launcher["validation"]
    if validation:
        lines += [f'  {validation["function"]}(']
        lines += [f"      {arg}" + (");" if index == len(validation["arguments"]) - 1 else ",")
                  for index, arg in enumerate(validation["arguments"])]
    for output in launcher["owned_outputs"]:
        expression = f'  auto {output["name"]} = {output["expression"]};'
        lines.extend(textwrap.wrap(expression, width=80, subsequent_indent="      ",
                                   break_long_words=False, break_on_hyphens=False))
    if backend == "npu":
        if launcher["bridge"] == "cached_op_api":
            symbol = launcher["symbol"]
            lines += ["  static const hyper_parallel::multicore::CachedOpApi api(",
                      f'      "{symbol}", "{symbol}GetWorkspaceSize");',
                      "  hyper_parallel::multicore::execute_cached_op(api,"]
        else:
            lines += [f'  EXEC_NPU_CMD_EXT({launcher["symbol"]},']
        lines += [f"      {arg}" + (");" if index == len(launcher["native_arguments"]) - 1 else ",")
                  for index, arg in enumerate(launcher["native_arguments"])]
    else:
        used = set(launcher["return_arguments"])
        if validation:
            used.update(validation["arguments"])
        lines += [f'  (void){arg["name"]};' for arg in entry["arguments"] if arg["name"] not in used]
    returns = launcher["return_arguments"]
    if len(returns) == 1:
        lines += [f"  return {returns[0]};"]
    else:
        lines += [f"  return {return_type}("]
        lines += [f"      {arg}" + (");" if index == len(returns) - 1 else ",")
                  for index, arg in enumerate(returns)]
    return "\n".join(lines)


def _functions(name, entry):
    return_type, declaration = _return_type(name, entry)
    lines = [declaration]
    for backend in ("npu", "meta"):
        lines += [f"{return_type} {_function_name(entry, backend)}("]
        for index, arg in enumerate(entry["arguments"]):
            kind = "at::Tensor&" if arg["write"] else _TYPES[arg["type"]]
            lines.append(f'    {kind} {arg["name"]}' + (") {" if index == len(entry["arguments"]) - 1 else ","))
        lines += [_body(entry, backend, return_type), "}", ""]
    return "\n".join(lines)


def _registration(entry):
    pieces = textwrap.wrap(entry["schema"], width=65, break_long_words=False, break_on_hyphens=False)
    return "m.def(\n" + "\n".join("    " + json.dumps(piece + (" " if index < len(pieces) - 1 else ""))
                                for index, piece in enumerate(pieces)) + ");\n"


def generated_files() -> dict[Path, str]:
    """Emit same-schema native/Meta function definitions and dispatcher registrations."""
    types = [_HEADER, "#pragma once", "#include <ATen/core/Tensor.h>", "#include <tuple>",
             "namespace hyper_parallel::multicore::generated {", "struct LauncherOutputs {"]
    for name, entry in _entries().items():
        if len(entry["returns"]) > 1:
            kind = "at::Tensor" if entry["launcher"]["owned_outputs"] else "at::Tensor&"
            types += [f"  using {name}_outputs = std::tuple<",
                      ",\n".join("      " + kind for _ in entry["returns"]) + ">;"]
    types += ["};", "}  // namespace hyper_parallel::multicore::generated", ""]
    files = {Path("torch/csrc/generated/launcher_types.hpp"): "\n".join(types)}
    for name, entry in _entries().items():
        files[Path(f"torch/csrc/generated/{name}_launcher.inc")] = _HEADER + _functions(name, entry)
        files[Path(f"torch/csrc/generated/{name}_schema.inc")] = _HEADER + _registration(entry)
    return files


def _definition(text, name):
    match = re.search(rf"\b{re.escape(name)}\s*\(", text)
    if match is None:
        raise ValueError(f"Original native launcher missing: {name}")
    start = text.rfind("\n", 0, match.start()) + 1
    opening = text.index("{", match.end())
    end, depth = opening + 1, 1
    while depth:
        depth += (text[end] == "{") - (text[end] == "}")
        end += 1
    return text[start:end]


def _verify_original(text, name, entry):
    launcher = entry["launcher"]
    npu = _definition(text, _function_name(entry, "npu"))
    signature = npu.split("(", 1)[1].split("{", 1)[0].rsplit(")", 1)[0]
    expected = ",".join(("at::Tensor&" if arg["write"] else _TYPES[arg["type"]]) + " " + arg["name"]
                        for arg in entry["arguments"])
    if _tokens(signature) != _tokens(expected):
        raise ValueError(f"Original native launcher type/mutation drift: {name}")
    if launcher["bridge"] == "cached_op_api":
        pattern = r"execute_cached_op\(api,\s*(.*?)\);"
        if json.dumps(launcher["symbol"]) not in npu:
            raise ValueError(f"Original native bridge symbol drift: {name}")
    else:
        pattern = rf'EXEC_NPU_CMD_EXT\({launcher["symbol"]},\s*(.*?)\);'
    call = re.search(pattern, npu, re.DOTALL)
    if call is None or _tokens(call[1]) != _tokens(",".join(launcher["native_arguments"])):
        raise ValueError(f"Original native launcher argument order drift: {name}")
    returned = re.search(r"return\s+(?:[\w:]+\((.*?)\)|(\w+))\s*;", npu, re.DOTALL)
    if returned is None or _tokens(returned[1] or returned[2]) != _tokens(",".join(launcher["return_arguments"])):
        raise ValueError(f"Original native launcher return order drift: {name}")


def adapt_launcher_source(text: str, family: str, filename: str) -> str:
    """Replace admitted definitions while preserving family validation and bridge implementations.

    Args:
        text: Original family adapter source.
        family: Supported native family.
        filename: Basename of the original adapter source.
    """
    for name, entry in _entries(family).items():
        if entry["launcher"]["source"] != filename:
            continue
        _verify_original(text, name, entry)
        npu = _definition(text, _function_name(entry, "npu"))
        meta = _definition(text, _function_name(entry, "meta"))
        text = text.replace(npu, f'#include "generated/{name}_launcher.inc"', 1).replace(meta, "", 1)
    return text.replace("#include <torch/library.h>",
                        '#include <torch/library.h>\n#include "generated/launcher_types.hpp"', 1)


def adapt_registration_source(text: str, family: str) -> str:
    """Generate registered schemas after checking their original mutable aliases and result order.

    Args:
        text: Original registration translation unit.
        family: Family whose two numerical operator schemas are replaced.
    """
    found = set()
    entries = _entries(family)
    def _replace(match):
        literals = re.findall(r'"(?:\\.|[^"\\])*"', match[0])
        if not literals:
            return match[0]
        schema = "".join(json.loads(literal) for literal in literals)
        name = schema.split("(", 1)[0]
        if name not in entries:
            return match[0]
        if str(torch._C.parse_schema(schema)) != entries[name]["schema"]:
            raise ValueError(f"Original dispatcher schema drift: {name}")
        found.add(name)
        return f'#include "generated/{name}_schema.inc"'
    text = re.sub(r"m\.def\(.*?\);", _replace, text, flags=re.DOTALL)
    if found != set(entries):
        raise ValueError(f"Missing original dispatcher schema: {family}")
    return text


def install_launcher_glue(root: Path, family: str) -> None:
    """Install generated entry definitions into an isolated native adapter source copy.

    Args:
        root: Isolated csrc directory containing the family's original sources.
        family: Native family to adapt.
    """
    entries = _entries(family)
    for filename in {entry["launcher"]["source"] for entry in entries.values()}:
        path = root / filename
        path.write_text(adapt_launcher_source(path.read_text(), family, filename))
    for filename in {entry["launcher"]["registration"] for entry in entries.values()}:
        path = root / filename
        path.write_text(adapt_registration_source(path.read_text(), family))
    generated = root / "generated"
    generated.mkdir(exist_ok=True)
    for relative, content in generated_files().items():
        if relative.name == "launcher_types.hpp" or any(relative.name.startswith(name + "_") for name in entries):
            (generated / relative.name).write_text(content)


def main() -> None:
    """Install launcher glue in the isolated adapter tree selected by the native builder."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--install-root", type=Path, required=True)
    parser.add_argument("--family", choices=("gate", "mhc", "moe"), required=True)
    args = parser.parse_args()
    install_launcher_glue(args.install_root, args.family)


if __name__ == "__main__":
    main()
