# Copyright 2026 Huawei Technologies Co., Ltd
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ============================================================================
"""Generate Python/C++ wire declarations and typed native calls from shared contracts."""

from __future__ import annotations

import argparse
import json
import re
import textwrap
from pathlib import Path

from hyper_parallel.core.multicore.runtime.abi import family_abi

CORE = Path(__file__).resolve().parents[1]
_CALLS = CORE / "runtime/native_calls.json"
_HEADER = (CORE / "runtime/abi.py").read_text().split('"""', 1)[0]
_CPP_HEADER = "// Copyright 2026 Huawei Technologies Co., Ltd.\n" + (
    "// Licensed under the Apache License, Version 2.0.\n"
    "// http://www.apache.org/licenses/LICENSE-2.0\n"
    "// Generated by backends.schema; edit the shared schemas instead.\n")
_CPP_NAMES = {"TensorDescC": "TensorDesc", "TaskDescC": "TaskDesc", "EventDescC": "EventDesc",
              "DynamicDataC": "DynamicData", "RuntimeConfigC": "RuntimeHeader"}
_ENUM_FIELDS = {"task_type": "TaskType", "task_aicore_type": "TaskAiCoreType",
                "event_type": "EventType", "dynamic_type": "DynamicType"}
_TYPES = {"uint32": "ctypes.c_uint32", "int32": "ctypes.c_int32",
          "uint64": "ctypes.c_uint64", "int64": "ctypes.c_int64"}
_ARG_TYPES = {"Tensor": "torch.Tensor", "int": "int", "float": "float", "bool": "bool"}


def _enums(family, calls):
    return {**calls["common_enums"], "TaskType": {binding.native_name: binding.numeric_id
                                              for binding in family_abi(family).task_types}}


def python_schema(family: str) -> str:
    """Emit self-contained ctypes declarations and family-local enums.

    Args:
        family: Supported native family name.
    """
    abi, calls = family_abi(family), json.loads(_CALLS.read_text())
    lines = [_HEADER, '"""Generated wire definitions; regenerate with backends.schema."""', "",
             "import ctypes", "from enum import IntEnum", "from typing import Any", ""]
    for name, values in _enums(family, calls).items():
        lines += ["", f"class {name}(IntEnum):", '    """Family wire enum from the shared schema."""', ""]
        lines += [f"    {key} = {value}" for key, value in values.items()]
    for structure in abi.structures:
        lines += ["", "", f"class {structure.name}(ctypes.Structure):",
                  '    """Family wire structure from the shared schema."""', "", "    _fields_ = ["]
        for field in structure.fields:
            kind = _TYPES.get(field.type, field.type)
            if field.count != 1:
                kind += f" * {field.count}"
            lines.append(f'        ("{field.name}", {kind}),')
        lines.append("    ]")
        if structure.name == "TaskDescC":
            lines += _task_defaults()
    return "\n".join(lines) + "\n"


def _task_defaults():
    return ["", "    def __init__(self, *args: Any, **kwargs: Any) -> None:",
            '        """Retain invalid profiling sentinels for descriptors without explicit ownership.',
            "", "        Args:", "            *args: Positional ctypes field values.",
            "            **kwargs: Named ctypes field values.", '        """',
            '        has_desc = len(args) >= len(self._fields_) - 1 or "profile_desc_id" in kwargs',
            '        has_owner = len(args) >= len(self._fields_) or "profile_owner_id" in kwargs',
            "        super().__init__(*args, **kwargs)", "        if not has_desc:",
            "            self.profile_desc_id = 0xFFFFFFFF", "        if not has_owner:",
            "            self.profile_owner_id = 0xFFFFFFFF"]


def cpp_schema(family: str) -> str:
    """Emit native wire types with every size/offset asserted from the same schema.

    Args:
        family: Supported native family name.
    """
    abi, calls = family_abi(family), json.loads(_CALLS.read_text())
    lines = [_CPP_HEADER, "#pragma once", "#include <cstddef>", "#include <cstdint>",
             "", "namespace MulticoreRuntime {"]
    for name, values in _enums(family, calls).items():
        lines += [f"enum class {name} : uint32_t {{", *(f"  {key} = {value}," for key, value in values.items()), "};"]
    for structure in abi.structures:
        name = _CPP_NAMES[structure.name]
        lines.append(f"struct {name} {{")
        for field in structure.fields:
            kind = calls["cpp_field_types"].get(f"{structure.name}.{field.name}", field.type)
            kind = _ENUM_FIELDS.get(field.name, _CPP_NAMES.get(kind, kind + "_t"))
            count = f"[{field.count}]" if field.count != 1 else ""
            lines.append(f"  {kind} {field.name.removeprefix('_')}{count};")
        lines += ["};", f'static_assert(sizeof({name}) == {structure.size}, "wire size mismatch");']
        lines += [f'static_assert(offsetof({name}, {field.name.removeprefix("_")}) == {field.offset}, '
                  '"wire offset mismatch");' for field in structure.fields]
    return _wrap_cpp("\n".join([*lines, "}  // namespace MulticoreRuntime", ""]))


def python_calls() -> str:
    """Emit typed Python launch functions in exact dispatcher schema order."""
    lines = [_HEADER, '"""Generated typed launch wrappers; edit runtime/native_calls.json."""', "",
             "import torch", "", "from hyper_parallel.core.multicore.runtime.bindings import resolve_native_call"]
    for name, entry in json.loads(_CALLS.read_text())["entries"].items():
        arguments = entry["arguments"]
        returns = "torch.Tensor" if len(entry["returns"]) == 1 else "tuple[torch.Tensor, ...]"
        lines += ["", "", f"def {name}("]
        lines += [f'    {arg["name"]}: {_ARG_TYPES[arg["type"]]},' for arg in arguments]
        lines += [f") -> {returns}:", '    """Launch the family entry through its verified dispatcher schema.', "",
                  "    Args:"]
        lines += [f'        {arg["name"]}: Native {arg["type"]} argument at position {index}.'
                  for index, arg in enumerate(arguments)]
        lines += ['    """', f'    return resolve_native_call("{name}")(']
        lines += [f'        {arg["name"]},' for arg in arguments]
        lines.append("    )")
    return "\n".join(lines) + "\n"


def cpp_calls() -> str:
    """Emit callable host wrappers preserving const/mutable Tensor argument ownership."""
    lines = [_CPP_HEADER, "#pragma once", "#include <cstdint>", "#include <utility>",
             "", "namespace hyper_parallel::multicore::generated {"]
    for name, entry in json.loads(_CALLS.read_text())["entries"].items():
        lines += ["template <typename Dispatcher, typename Tensor>",
                  f"inline decltype(auto) {name}(Dispatcher&& dispatch,"]
        for index, arg in enumerate(entry["arguments"]):
            kind = ("Tensor&" if arg["write"] else "const Tensor&") if arg["type"] == "Tensor" else {
                "int": "int64_t", "float": "double", "bool": "bool"}[arg["type"]]
            suffix = ") {" if index == len(entry["arguments"]) - 1 else ","
            lines.append(f'    {kind} {arg["name"]}{suffix}')
        lines.append("  return std::forward<Dispatcher>(dispatch)(")
        for index, arg in enumerate(entry["arguments"]):
            suffix = ");" if index == len(entry["arguments"]) - 1 else ","
            lines.append(f'      {arg["name"]}{suffix}')
        lines += ["}", ""]
    lines += ["}  // namespace hyper_parallel::multicore::generated", ""]
    return _wrap_cpp("\n".join(lines))


def generated_files() -> dict[Path, str]:
    """Return deterministic repository-relative artifacts for all three families."""
    files = {Path(f"runtime/generated/{family}_abi.py"): python_schema(family) for family in ("gate", "mhc", "moe")}
    files.update({Path(f"ops/runtime/generated/{family}_schema.hpp"): cpp_schema(family)
                  for family in ("gate", "mhc", "moe")})
    files[Path("runtime/generated/native_calls.py")] = python_calls()
    files[Path("ops/runtime/generated/native_calls.hpp")] = cpp_calls()
    return files


def adapt_cpp_schema(text: str, family: str) -> str:
    """Replace legacy declarations while preserving all native accessor/worker behavior.

    Args:
        text: Verified original runtime header source.
        family: Family whose schema defines the replacement types.
    """
    if family == "moe":
        start = text.index("enum class TaskAiCoreType")
        end = text.index("__aicore__ inline uint32_t getTaskNum", start)
        ready = re.search(r"struct ReadyHandshakeMeta\s*\{[^}]*\};", text).group()
        text = text[:start] + ready + "\n\n" + text[end:]
    else:
        names = (*_enums(family, json.loads(_CALLS.read_text())), *_CPP_NAMES.values())
        for name in names:
            pattern = rf"(?:enum\s+(?:class|struct)|struct)\s+{name}\s*[^{{;]*\{{[^}}]*\}};"
            text, count = re.subn(pattern, "", text, count=1)
            if count != 1:
                raise ValueError(f"Missing native declaration during schema installation: {name}")
    start = text.index("__aicore__ inline void getTaskDesc")
    end = text.index("__aicore__", start + len("__aicore__"))
    reader = text[start:end]
    for old, new in (("tilingData", "task"), ("start_size", "pos"),
                     ("tensor_desc_size", "tensor_size"), ("task_desc_size", "task_size")):
        reader = re.sub(rf"\b{old}\b", new, reader)
    text = text[:start] + reader + text[end:]
    text = text.replace("MULTICORE_SCHEDULER_RUNTIME_CONFIG_HPP",
                        "HYPER_PARALLEL_CORE_MULTICORE_OPS_RUNTIME_RUNTIME_CONFIG_HPP_")
    return _wrap_cpp(text.replace("namespace MulticoreRuntime {", f'#include "generated/{family}_schema.hpp"\n\n'
                                 "namespace MulticoreRuntime {", 1))


def _wrap_cpp(text):
    text = re.sub(r"(__aicore__ inline [^\n{]+)\{([^}\n]+)\}",
                  lambda match: match[1].rstrip() + " {\n  " + match[2].strip() + "\n}", text)
    result, block_comment = [], False
    for line in text.splitlines():
        stripped = line.lstrip()
        indent = line[:len(line) - len(stripped)]
        if block_comment or stripped.startswith(("/*", "//")):
            prefix = indent + ("// " if stripped.startswith("//") else "* ")
            result.extend(textwrap.wrap(line, width=80, subsequent_indent=prefix,
                                        break_long_words=False, break_on_hyphens=False) or [line])
            block_comment = "*/" not in line and (block_comment or stripped.startswith("/*"))
            continue
        if stripped.startswith("#"):
            result.append(line)
            continue
        result.extend(_wrap_cpp_code(line, indent))
    return "\n".join(result) + "\n"


def _wrap_cpp_code(line, indent):
    tokens = re.findall(r"\"(?:\\.|[^\"\\])*\"|'(?:\\.|[^'\\])*'|//.*|\s+|[^\s\"']+", line)
    joined = []
    for token in tokens:
        if token.startswith(")") and joined and not joined[-1].isspace():
            joined[-1] += token
        else:
            joined.append(token)
    result, current = [], ""
    for token in joined:
        if token.startswith("//"):
            prefix = indent + "// "
            result.extend(textwrap.wrap(current + token, width=80, subsequent_indent=prefix,
                                        break_long_words=False, break_on_hyphens=False))
            return result
        if len(current) + len(token) > 80 and current.strip() and not token.isspace():
            result.append(current.rstrip())
            current = indent + "  " + token
        else:
            current += token
    result.append(current.rstrip())
    return result


def install_cpp_schema(runtime: Path, family: str) -> None:
    """Install same-schema types into an already verified isolated source export.

    Args:
        runtime: Assembled private runtime header directory.
        family: Native family whose original ABI is preserved.
    """
    header = runtime / "runtime_config.hpp"
    text = adapt_cpp_schema(header.read_text(), family)
    generated = runtime / "generated"
    generated.mkdir(exist_ok=True)
    (generated / f"{family}_schema.hpp").write_text(cpp_schema(family))
    header.write_text(text)


def main() -> None:
    """Write generated artifacts or fail if checked-in output has drifted."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    for relative, content in generated_files().items():
        path = CORE / relative
        if args.check:
            if not path.is_file() or path.read_text() != content:
                raise ValueError(f"Generated native schema drift: {relative}")
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)


if __name__ == "__main__":
    main()
