# Copyright 2026 Huawei Technologies Co., Ltd
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ============================================================================
"""Generate verified family worker dispatch, input slots and owned context declarations."""

from __future__ import annotations

import json
import re
from pathlib import Path

from hyper_parallel.core.multicore.backends import contexts
from hyper_parallel.core.multicore.runtime.abi import family_abi

CORE = Path(__file__).resolve().parents[1]
_CONTRACTS = CORE / "runtime/worker_calls.json"
_HEADER = (
    "// Copyright 2026 Huawei Technologies Co., Ltd.\n"
    "// Licensed under the Apache License, Version 2.0.\n"
    "// http://www.apache.org/licenses/LICENSE-2.0\n"
    "// Generated by backends.workers; edit runtime/worker_calls.json.\n"
)


def _contracts():
    data = json.loads(_CONTRACTS.read_text())
    if data["format_version"] != 1:
        raise ValueError("Unsupported native worker schema version")
    for name, worker in data["workers"].items():
        known = {
            binding.native_name for binding in family_abi(worker["family"]).task_types
        }
        tasks = [task for case in worker["cases"] for task in case["tasks"]]
        if len(tasks) != len(set(tasks)) or not set(tasks).issubset(known):
            raise ValueError(
                f"Native worker has duplicate or unknown task bindings: {name}"
            )
        if worker["mode"] == "task_dag":
            addresses = worker["input_addresses"]
            if any(
                index >= len(addresses) or index < 0
                for index in worker["constants"].values()
            ):
                raise ValueError(
                    f"Native worker slot exceeds its input address table: {name}"
                )
    return data["workers"]


def worker_manifest(family: str) -> dict[str, object]:
    """Describe native callbacks, address slots and existing context ownership.

    Args:
        family: Supported native worker family.
    """
    workers = {
        name: worker
        for name, worker in _contracts().items()
        if worker["family"] == family
    }
    if not workers:
        raise ValueError(f"Unsupported native worker family: {family}")
    bindings = {
        binding.native_name: binding for binding in family_abi(family).task_types
    }
    result = {}
    for name, worker in workers.items():
        tasks = [
            {
                "native_name": task,
                "numeric_id": bindings[task].numeric_id,
                "logical_name": bindings[task].logical_name,
                "call": case["call"],
            }
            for case in worker["cases"]
            for task in case["tasks"]
        ]
        result[name] = {**worker, "task_bindings": tasks}
    return {"format_version": 1, "family": family, "workers": result}


def _fragments(worker):
    lines = [f"switch ({worker['selector']}) {{"]
    for case in worker["cases"]:
        lines.extend(
            f"  case {worker['task_namespace']}TaskType::{task}:"
            for task in case["tasks"]
        )
        if case["call"]:
            lines.append(f"    {case['call']};")
        lines.append("    break;")
    lines += ["  default:", f"    {worker['default']}", "}"]
    result = {"dispatch": "\n".join(lines) + "\n"}
    if worker["constants"]:
        result["slots"] = "".join(
            f"static constexpr uint32_t {name} = {index};\n"
            for name, index in worker["constants"].items()
        )
        result["inputs"] = f"GM_ADDR {worker['input_array']}[] = {{\n"
        result["inputs"] += "".join(
            f"  {address},\n" for address in worker["input_addresses"]
        )
        result["inputs"] += "};\n"
    if worker["members"]:
        result["members"] = "".join(
            f"{member['type']} {member['name']}"
            + (
                f" = {member['initializer']}"
                if member["initializer"] is not None
                else ""
            )
            + ";\n"
            for member in worker["members"]
        )
    return result


def generated_files() -> dict[Path, str]:
    """Emit deterministic fragments included directly by existing native worker classes."""
    files = {
        Path(f"ops/runtime/generated/{name}_{kind}.inc"): _HEADER + text
        for name, worker in _contracts().items()
        for kind, text in _fragments(worker).items()
    }
    files.update(contexts.generated_files())
    return files


def _tokens(text):
    pattern = r'"(?:\\.|[^"\\])*"|/\*.*?\*/|//[^\n]*|\w+|[^\s]'
    return [
        token
        for token in re.findall(pattern, text, re.DOTALL)
        if not token.startswith(("//", "/*"))
    ]


def _checked_include(text, original, expected, name, kind):
    if _tokens(original) != _tokens(expected):
        raise ValueError(f"Native worker {kind} contract drift: {name}")
    return text.replace(original, f'#include "runtime/generated/{name}_{kind}.inc"', 1)


def _dispatch_block(text):
    start = text.index("switch (", text.index("void ExecuteComputeKernel"))
    opening = text.index("{", start)
    depth = 1
    end = opening + 1
    while depth:
        depth += (text[end] == "{") - (text[end] == "}")
        end += 1
    return text[start:end]


def adapt_native_worker(text: str, name: str) -> str:
    """Replace only verified dispatch, slot constants and owned members with generated includes.

    Args:
        text: Fixed-revision native worker source, already verified by the family builder.
        name: Family and direction key in the worker schema.
    """
    worker = _contracts()[name]
    fragments = _fragments(worker)
    text = _checked_include(
        text, _dispatch_block(text), fragments["dispatch"], name, "dispatch"
    )
    for kind in ("slots", "members"):
        if kind not in fragments:
            continue
        if kind == "slots":
            names = "|".join(worker["constants"])
            pattern = rf"static constexpr uint32_t (?:{names}) = \d+;"
        else:
            names = "|".join(member["name"] for member in worker["members"])
            pattern = rf"(?:HyperMegaGate::\w+|uint32_t) (?:{names})(?: = \d+)?;"
        matches = list(re.finditer(pattern, text))
        original = text[matches[0].start() : matches[-1].end()] if matches else ""
        text = _checked_include(text, original, fragments[kind], name, kind)
    return text


def adapt_native_entry(text: str, name: str) -> str:
    """Generate the exact native input address table without changing kernel enqueue order.

    Args:
        text: Verified original family kernel entry source.
        name: TaskDAG family and direction key in the worker schema.
    """
    worker = _contracts()[name]
    original = re.search(
        r"GM_ADDR\s+(?:input_list|inputList)\[\]\s*=\s*\{.*?\};", text, re.DOTALL
    )
    if original is None:
        raise ValueError(f"Native worker input address table missing: {name}")
    # A final array comma has no meaning; normalize the original before comparison.
    table = re.sub(r",\s*\};", "};", original.group())
    expected = re.sub(r",\s*\};", "};", _fragments(worker)["inputs"])
    _checked_include(text, table, expected, name, "inputs")
    return text.replace(
        original.group(), f'#include "runtime/generated/{name}_inputs.inc"', 1
    )


def install_worker_glue(operator: Path, family: str, direction: str) -> None:
    """Install generated fragments into a verified isolated native operator export.

    Args:
        operator: Family operator directory containing its op_kernel sources.
        family: Native numerical family.
        direction: Forward or backward entry selection.
    """
    name = f"{family}_{direction}"
    worker = _contracts()[name]
    kernel = operator / "op_kernel"
    runtime = kernel / "runtime/generated"
    runtime.mkdir(parents=True, exist_ok=True)
    for relative, content in generated_files().items():
        if relative.name.startswith(name + "_"):
            (runtime / relative.name).write_text(content)
    path = kernel / Path(worker["source"]).name
    path.write_text(adapt_native_worker(path.read_text(), name))
    if worker["mode"] == "task_dag":
        path = kernel / Path(worker["entry_source"]).name
        path.write_text(adapt_native_entry(path.read_text(), name))
    contexts.install_context_glue(kernel, name)
